modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="project_tardis"
version="1.0.0"
displayName="Project TARDIS 2.0"
displayURL="https://mcreator.net"
credits="Credits to Taygamerlol - Developer , TheGoldenFoxy - Head Dev, Model Designer"
authors="Taygamerlol, Evilguardian667"
description="Additions to New Tardis Mod"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.project_tardis]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration
